apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patchesStrategicMerge:
  - deployment.yaml
  - service.yaml
replicas:
  - name: vote
    count: 7
images:
  - name: schoolofdevops/vote
    newName: matiasadrian4/vote
    newTag: main-03576bba-1772831423 # {"$imagepolicy": "flux-system:vote:tag"}
    #newName: lfs269/vote
    #digest: sha256:abcd1234efgh5678ijkl9101mnopqrstuvwx2345yzab6789cdef0123ghij4567
namespace: instavote
commonLabels:
  project: instavote
  env: staging
commonAnnotations:
  supported-by: "sre@example.com"
configMapGenerator:
  - name: vote-options
    env: options.env
